### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by ivanhercaz** [ivanhercaz/tricko#1]
This is the roadmap to achieve to release the first version (0.1.0) of Tricko. This version is planned to be a sketch of the idea in which we are working. Of course, anyone is welcome to test the app, submit issues and proposals, or ask any doubt.

- [x] Take a ticket for turns.
- [x] Configuration file in YAML.
- [x] Three personalized options of turns.
- [x] Print in the screen:
  - [x] Number of turns taken.
  - [x] Options to take a turn and their next numbers.
  - [x] Number just taken and a QR code. 
- [x] `Makefile` to make easier the installation of the requirements to use the app (issues related: #7).
- [ ] README should describe the necessary steps to install, use and contribute to the development of Tricko (#2).
- [x] `requirements.txt` file to install the dependencies to use Tricko (#6).
- [x] Option to make it globally available (#7).
- [x] Refactor the current code (#8).
- [ ] Package/testing (#4)
  - [ ] Android (#5)
  - [ ] Windows (#12)
- [ ] Multilingual support (#3).
- [ ] Split the take number from the monitor of tickets taken (#13).
- [x]  Buttons configuration with different layouts (#14)

If I am forgetting something to include in this release, you can comment it in this issue.
