### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by ivanhercaz** [ivanhercaz/tricko#3]
I have thought about if Tricko should have multilingual support from the first release we are planing. At least for the moments the strings to translate aren't very much and some of them (the type of ticket) can be adjusted to the desired language easily in the `config.yaml` file.

To address this issue we should think about the next questions:

- Should we add multilingual support in 0.1.0?
- Should we integrate all the strings in the `config.yaml`? Or, should we use any of the Python libraries available for i18n?
- Either in 0.1.0 or in a future release, what languages should be add? I think we can work easily with English, Portuguese and Spanish, and for another languages we could ask for translations.

**Decision after the comment by @Pablohn26**

- Yes, this feature should be in 0.1.0
- With some Python library to manage i18n.
- Minimum in English, Portuguese and Spanish.

**Tasks**

- [ ] i18n mechanism for Tricko.
- [ ] Buttons to choose the language.
- [ ] Configuration in the `config.yaml` to show or not the buttons to change the language according to the decision of the administrator.
- [ ] Translate to Spanish and Portuguese (base language will be English).

**Further readings**
- [A complete guide to i18n in Python](https://www.mattlayman.com/blog/2015/i18n/) from the Matt Layman's blog.
- [Internationalization](https://docs.python.org/3.7/library/i18n.html) from the documentation of The Python Standard Library.
- [danhper/python-i18n](https://github.com/danhper/python-i18n), an easy to use i18n library for Python, although it seems outdated (last release at 1 Jul 2014)
- [tito/kivy-gettext-example](https://github.com/tito/kivy-gettext-example), example for an internationalized Kivy application.
